version: "3"
services:
  # my-app:
  # image: ${docker-registry}/my-app:1.0
  # ports:
  # - 3000:3000

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - "mongodb"
  ui-service:
    image: ui-service # This explicitly sets the image name to "ui-service"
    build:
      context: ./app # The build context
      dockerfile: ../Dockerfile # Relative path to the Dockerfile from the build context
    volumes:
      - ./home/app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - "mongodb"
volumes:
  mongo-data:
    driver: local
